[package]
name = "maky"
version = "0.1.0"
edition = "2021"
authors = ["Aytixel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
toml = "0.7.3"
clap = { version = "4.2.1", features = ["derive"] }
blake3 = "1.3.3"
