[package]
name = "maky"
version = "0.1.0"
edition = "2021"
authors = ["Aytixel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.3"
pretok = "0.1.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_with = "3.0.0"
serde_regex = "1.1.0"
toml = "0.8.8"
clap = { version = "4.2.1", features = ["derive"] }
blake3 = "1.3.3"
crossterm = "0.27.0"
kdam = { version = "0.5.0", features = ["rich", "spinner"] }
ahash = { version = "0.8.3", features = ["serde"] }
hyperscan = "0.3.2"
once_cell = "1.18.0"
pkg-config = "0.3.27"
