mod commands;
mod config;
mod helpers;

use std::{
    fmt::Display,
    io::{self, stderr},
};

use clap::{command, Parser, Subcommand};
use crossterm::{
    execute,
    style::{Print, Stylize},
};

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None, styles=get_styles())]
struct Command {
    #[command(subcommand)]
    subcommand: SubCommand,
}

#[derive(Subcommand, Debug)]
enum SubCommand {
    /// Initialize a new maky package directory
    Init {
        #[clap(flatten)]
        command: commands::init::Command,
    },

    /// Build files
    Build {
        #[clap(flatten)]
        command: commands::build::Command,
    },

    /// Build files then run the specified file
    Run {
        #[clap(flatten)]
        command: commands::run::Command,
    },

    /// Remove artifacts generated by maky in the past
    Clean {
        #[clap(flatten)]
        command: commands::clean::Command,
    },
}

#[tokio::main]
async fn main() -> io::Result<()> {
    if let Err(error) = execute_command().await {
        print_error(error)?;
    }

    Ok(())
}

async fn execute_command() -> anyhow::Result<()> {
    kdam::term::init(true);

    let command = Command::parse();

    match command.subcommand {
        SubCommand::Init { command } => command.execute().await?,
        SubCommand::Build { command } => command.execute().await?,
        SubCommand::Run { command } => todo!(),
        SubCommand::Clean { command } => todo!(),
    }

    return Ok(());
}

fn print_error<T: Display>(error: T) -> io::Result<()> {
    execute!(
        stderr(),
        Print("error".dark_red().bold()),
        Print(": ".bold()),
        Print(error.to_string().reset()),
        Print("\n"),
    )
}

fn get_styles() -> clap::builder::Styles {
    clap::builder::Styles::styled()
        .usage(clap::builder::styling::Style::new().bold().fg_color(Some(
            clap::builder::styling::Color::Ansi(clap::builder::styling::AnsiColor::Green),
        )))
        .header(clap::builder::styling::Style::new().bold().fg_color(Some(
            clap::builder::styling::Color::Ansi(clap::builder::styling::AnsiColor::Green),
        )))
        .literal(clap::builder::styling::Style::new().bold().fg_color(Some(
            clap::builder::styling::Color::Ansi(clap::builder::styling::AnsiColor::Cyan),
        )))
        .invalid(clap::builder::styling::Style::new().bold().fg_color(Some(
            clap::builder::styling::Color::Ansi(clap::builder::styling::AnsiColor::Red),
        )))
        .error(clap::builder::styling::Style::new().bold().fg_color(Some(
            clap::builder::styling::Color::Ansi(clap::builder::styling::AnsiColor::Red),
        )))
        .valid(
            clap::builder::styling::Style::new()
                .bold()
                .underline()
                .fg_color(Some(clap::builder::styling::Color::Ansi(
                    clap::builder::styling::AnsiColor::Cyan,
                ))),
        )
        .placeholder(clap::builder::styling::Style::new().fg_color(Some(
            clap::builder::styling::Color::Ansi(clap::builder::styling::AnsiColor::Cyan),
        )))
}
